### ISSUE TITLE
Gained sentience

### ISSUE THREAD

**Issue by akaptur** [akaptur/emoji-bot#4]
Emoji-bot should only respond to PMs initiated by others. Instead, it gained sentience, became lonely, and reached out to lots of people. It should not do this.

**Comment by alexandrinaw** [comment]
I think the bot got subscribed to a new stream? Can that even happen? Somehow it has something to do with the Library stream. I got a message from rainbot right after I posted a message in that stream, and it seems like the other people who have also reported this issue are the same people who have posted in Library.

**Comment by akaptur** [comment]
@alexandrinaw ah, thanks! I bet that's exactly what happened - the bot wasn't subscribed to any streams initially, so the only messages it received were PMs. Someone created a new stream and added everyone (including bots) to it, which meant the bot got notified about messages to that stream.  The bot thinks that all messages are PMs, so it started sending PMs "back" to all senders of messages in the new stream. I didn't anticipate that.
Looking at [these docs](https://gist.github.com/rsms/206437566a81bb076c02) suggests that the right thing to do is filter on a message's `{'type': private}` keyword.
